//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OraclePerfTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("211.171.200.221")]
        public string ServerIp {
            get {
                return ((string)(this["ServerIp"]));
            }
            set {
                this["ServerIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1521")]
        public string ServerPort {
            get {
                return ((string)(this["ServerPort"]));
            }
            set {
                this["ServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ALADIN")]
        public string DatabaseName {
            get {
                return ((string)(this["DatabaseName"]));
            }
            set {
                this["DatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MANNA")]
        public string DatabaseId {
            get {
                return ((string)(this["DatabaseId"]));
            }
            set {
                this["DatabaseId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ekswnr59")]
        public string DatabasePassword {
            get {
                return ((string)(this["DatabasePassword"]));
            }
            set {
                this["DatabasePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal UserCount {
            get {
                return ((decimal)(this["UserCount"]));
            }
            set {
                this["UserCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string QueryRate {
            get {
                return ((string)(this["QueryRate"]));
            }
            set {
                this["QueryRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT /*+ LEADING(A) INDEX(A MN_A1_TODAY_IX_4) USE_NL(B) INDEX(B MN_A1_TODAY_ADD" +
            "_PK) NLJ_BATCHING */\r\n       A.ORD_NO,\r\n       A.ORD_TODAY_NO,\r\n       A.ORD_TOD" +
            "AY_ADD_NO,\r\n       A.ORD_TODAY_ALL_NO,\r\n       A.ORD_TYPE_CD,\r\n       A.ORD_STAT" +
            "US_CD,\r\n       A.ORD_DATE,\r\n       A.MOD_DATE,\r\n       A.PICKUP_DATE,\r\n       A." +
            "TAKEOUT_DATE,\r\n       A.END_DATE,\r\n       A.ORD_CU_TEL,\r\n       A.ORD_CU_END_CNT" +
            ",\r\n       A.EA_ADDR_4,\r\n       A.DVRY_DISTANCE,\r\n       A.DVRY_AMT,\r\n       A.OR" +
            "D_AMT,\r\n       A.DISCOUNT_AMT,\r\n       A.SRV_AMT,\r\n       A.CHARGE_TYPE,\r\n      " +
            " A.PAY_TYPE_CD,\r\n       A.PAY_AMT,\r\n       A.PAY_MILEAGE,\r\n       B.TRAN_TYPE,\r\n" +
            "       A.CTH_WK_NAME,\r\n       A.CTH_WK_TEL,\r\n       A.ORD_MEMO,\r\n       B.CTH_ST" +
            "_NAME,\r\n       A.DVRY_CNT,\r\n       A.ORD_PATH_CD,\r\n       B.CTH_ST_TEL,\r\n       " +
            "B.ORD_CU_NAME,\r\n       A.TAKEOUT_YN,\r\n       A.ORD_ST_CODE,\r\n       A.ORD_ST_NAM" +
            "E,\r\n       A.DVRY_TYPE_CD,\r\n       A.XY_ACC_TYPE,\r\n       A.EA_ADDR_5,\r\n       A" +
            ".READY_TIME,\r\n       A.GOODS_NAMES,\r\n       A.ORG_PAY_TYPE,\r\n       A.CASH_MOVE_" +
            "CNT,\r\n       A.CASH_MOVE_AMT,\r\n       B.ORD_BR_CODE,\r\n       A.EA_ADDR_6,\r\n     " +
            "  A.EA_ADDR_7,\r\n       A.PUT_USER_ID,\r\n       B.CTH_BR_CODE,\r\n       B.CTH_ST_CO" +
            "DE,\r\n       A.CTH_WK_ARR_TIME,\r\n       A.CTH_DATE,\r\n       A.READY_CHANGE_DATE,\r" +
            "\n       A.CTH_DVRY_TYPE_CD,\r\n       A.DVRY_LOCK_TIME,\r\n       A.ST_DVRY_TYPE_CD," +
            "\r\n       B.ORD_CU_MULTI_END_CNT,\r\n       A.DVRY_EX_CHARGE,\r\n       A.DVRY_MNG_TY" +
            "PE,\r\n       A.DVRY_MNG_FEE,\r\n       B.VAN_TYPE_CD,\r\n       B.CARD_APPR_NUM,\r\n   " +
            "    A.MOD_USER_ID,\r\n       B.ORD_MASTER_ST_CODE,\r\n       B.CTH_MNG_BR_CODE,\r\n   " +
            "    B.CTH_MNG_HD_CODE,\r\n       B.ORD_HD_CODE,\r\n       A.EA_ADDR_MOD_CNT,\r\n      " +
            " A.CTH_WK_ARR_DATE,\r\n       A.READY_CTH_YN,\r\n       A.CALL_ST_CODE,\r\n       A.SA" +
            "_LAT_Y,\r\n       A.SA_LNG_X,\r\n       A.CANCEL_DATE,\r\n       A.SA_APP_ADDR,\r\n     " +
            "  A.POS_ORD_CODE,\r\n       B.EA_ADDR_10,\r\n       A.CTH_WK_CODE,\r\n       B.ACQUIRE" +
            "R_NAME,\r\n       A.EA_LAT_Y,\r\n       A.EA_LNG_X,\r\n       B.ORD_BR_NAME,\r\n       A" +
            ".CU_050_NUM,\r\n       TO_CHAR (A.ORD_DATE, \'YYYYMMDDHH24MISS\')\r\n           AS CUS" +
            "TOM_ORD_DATE,\r\n       TO_CHAR (A.READY_CHANGE_DATE, \'YYYYMMDDHH24MISS\')\r\n       " +
            "    AS CUSTOM_READY_CHANGE_DATE,\r\n       TO_CHAR (A.CTH_WK_ARR_DATE, \'YYYYMMDDHH" +
            "24MISS\')\r\n           AS CUSTOM_CTH_WK_ARR_DATE,\r\n       TO_CHAR (A.PICKUP_DATE, " +
            "\'YYYYMMDDHH24MISS\')\r\n           AS CUSTOM_PICKUP_DATE,\r\n       TO_CHAR (A.END_DA" +
            "TE, \'YYYYMMDDHH24MISS\')\r\n           AS CUSTOM_END_DATE,\r\n       TO_CHAR (A.CANCE" +
            "L_DATE, \'YYYYMMDDHH24MISS\')\r\n           AS CUSTOM_CANCEL_DATE,\r\n       TO_CHAR (" +
            "A.CTH_DATE, \'YYYYMMDDHH24MISS\')\r\n           AS CUSTOM_CTH_DATE,\r\n       TO_CHAR " +
            "(A.MOD_DATE, \'YYYYMMDDHH24MISS\')\r\n           AS CUSTOM_MOD_DATE,\r\n       TO_CHAR" +
            " (A.MOD_DATE, \'YYYYMMDDHH24MISSFF3\')\r\n           AS CUSTOM_MOD_DATE_FF3,\r\n      " +
            " TRUNC (A.DVRY_DISTANCE / 1000, 1)\r\n           AS CUSTOM_DVRY_DISTANCE,\r\n       " +
            "B.EA_ADDR_STR,\r\n       A.ORG_ORD_NO,\r\n       A.ORG_ORD_PATH_CD,\r\n       B.VAN_TY" +
            "PE_STR\r\n           AS ARR_VAN_TYPE_CD,\r\n       TO_CHAR (A.PUT_DATE, \'YYYYMMDDHH2" +
            "4MISS\')\r\n           AS CUSTOM_PUT_DATE,\r\n       A.ORD_DATA_YN,\r\n       A.DVRY_TA" +
            "X_YN,\r\n       A.DVRY_NLT_TYPE,\r\n       B.ST_DVRY_HD_CODE,\r\n       B.ST_DVRY_BR_C" +
            "ODE,\r\n       A.CHARGE_HISTORY,\r\n       A.ARR_TIME,\r\n       A.DVRY_GRP_TYPE,\r\n   " +
            "    A.ORD_ST_TEL,\r\n       A.PRE_CTH_YN,\r\n       A.CTH_WK_GOODS_PAY_TYPE,\r\n      " +
            " A.MOD_SEQ_NO,\r\n       A.EXT_ORD_NO\r\n  FROM MN_A1_TODAY A, MN_A1_TODAY_ADD B\r\n W" +
            "HERE     A.ORD_NO = B.ORD_NO\r\n       AND A.ORD_DATA_YN = \'Y\'\r\n       AND A.MOD_D" +
            "ATE >= TO_DATE (\'20190814173544\', \'YYYYMMDDHH24MISS\')")]
        public string Query {
            get {
                return ((string)(this["Query"]));
            }
            set {
                this["Query"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QueryArguments {
            get {
                return ((string)(this["QueryArguments"]));
            }
            set {
                this["QueryArguments"] = value;
            }
        }
    }
}
